### ISSUE TITLE
Add a timeout to all shelljs exec

### ISSUE THREAD

**Issue by aboutte** [perforce/setup-p4#4]
Depending on what arguments are used it is possible `p4` will expect user input forever.  An example is the following:

```
      - name: p4 submit
        uses: setup-p4
        id: submit
        env:
          P4CLIENT: ci
        with:
          command: submit
          global_options: -I
          working_directory: "C:/Users/perforce/Perforce/ci/Game/"
```

Without `-d` being included in `arguments` p4 expects input from an interactive user.
