### ISSUE TITLE
Remove `setup` input

### ISSUE THREAD

**Issue by aboutte** [perforce/setup-p4#49]
The `setup` input was used originally to ease some of the javascript but it is really unnecessary. Now that we are getting close to releasing and we are focusing on ease of use for the end user we should remove this input. 

The new plan is to always run the setup routine and rely on caching to keep step execution fast.  The different use cases that need to be supported are:

1. if `p4_version` is not changed then the default version will get installed with the very first `setup-p4` step
2. if `p4_version` is changed in the first step we will install the requested version
3. if `p4_version` is changed in a subsequent step we will download and install the secondary version
4. if `p4_version` is left as default for step A, changed in step B, and again left as default in step C then in step C we should use the cached version in the step A

1) 
```
  smoke:
    name: smoke
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: p4 info 21.2
        uses: ./
        with:
          command: -V
```

2)
```
  smoke:
    name: smoke
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: p4 info 20.1
        uses: ./
        with:
          p4_version: 20.1
          command: -V
```

3)
```
  smoke:
    name: smoke
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: p4 info 21.2
        uses: ./
        with:
          command: -V
      - name: p4 info 20.1
        uses: ./
        with:
          p4_version: 20.1
          command: -V
```

4)
```
  smoke:
    name: smoke
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: p4 info 21.2
        uses: ./
        with:
          command: -V
      - name: p4 info 20.1
        uses: ./
        with:
          p4_version: 20.1
          command: -V
      - name: p4 info 21.2
        uses: ./
        with:
          command: -V
```
