### ISSUE TITLE
Expand-Archive : is not a supported archive file format. .zip is the only supported archive file format.

### ISSUE THREAD

**Issue by aboutte** [perforce/setup-p4#7]
# Expected Behavior

p4 gets installed on self hosted windows runner

## Current Behavior

```
Expand-Archive : is not a supported archive file format. .zip is the only supported archive file format.
```

## Steps to Reproduce

```
      - name: p4 setup
        id: setup
        with:
          command: setup
          p4_version: 21.2
```

## Environment

self hosted windows 2019 runner
